/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cloud_logic_custom: [
    {
      name: "betterTogetherAPI",
      endpoint: "https://2dbflimh5a.execute-api.us-east-1.amazonaws.com/prod",
      region: "us-east-1",
    },
  ],
};

export default awsmobile;
